{% set name = "lifetimes" %}
{% set version = "0.11.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Lifetimes-{{ version }}.tar.gz
  sha256: 15af22b130ed0cc6148d8ae4eb9b0f9c8c9bc9c952dd4ce68a1da0bc4c80c712

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - autograd >=1.2.0
    - dill >=0.2.6
    - numpy >=1.10.0
    - pandas >=0.24.0
    - scipy >=1.0.0

test:
  imports:
    - lifetimes
    - lifetimes.datasets
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/CamDavidsonPilon/lifetimes
  license: MIT
  license_family: MIT
  license_file: README.md
  summary: Measure customer lifetime value in Python
  doc_url: https://lifetimes.readthedocs.io/en/latest/?badge=latest

extra:
  recipe-maintainers:
    - CamDavidsonPilon
    - Arnoldosmium
